Tasks 1,2,3 of block Components
js-tasks-ru/vue-20200925-2_nakonsta pull request #3
Opened 2020-10-05 13:59 UTC by Nakonsta

2020-10-05 14:06 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover должен иметь необязательные строковые параметры link и title
+ MeetupCover должен выводить изображение митапа
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен иметь необязательный строковый параметр description
+ MeetupDescription должен выводить описание митапа
+ MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
+ MeetupInfo должен выводить краткое описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
+ MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
+ MeetupAgendaItem должен выводить время
+ MeetupAgendaItem должен выводить заголовок по умолчанию
+ MeetupAgendaItem должен выводить правильную иконку для регистрации
+ MeetupAgendaItem должен выводить доклад
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный параметр meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 недель для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
+ MeetupsCalendar должен вывести май 2020
+ MeetupsCalendar должен вывести июнь 2020
+ MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
+ MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
+ MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по ум��лчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-05 14:53 UTC, ShGKme requested changes
Задача MeetupPageComponent принята 👍

По задаче CounterButton требуются комментарии и небольшие исправления.

В задаче MeetupsCalendar требуется концептуально важное исправление.

2020-10-05 14:53 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    increaseCount: function(countNum) {
Какую роль играет этот аргумент? Нужен ли он в решении задачи?

2020-10-05 14:53 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +            <a v-for="title in getMeetupsAtDay(\`\${pastDay}\`, dateInfo.currentMonth, 'past')" class="rangepicker__event">{{ title }}</a>
Вызывать методы в шаблоне - плохая практика.
Здесь должно быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут вызываться только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кешируется. 

Кроме того, это не декларативно. Нам требуется описать шаблон, который декларирует, описывает, какое отображение (HTML) мы хотим получить. А вызов метода - это императивный путь, мы говорим, что нужно сделать, чтобы получить данные, необходимые для формирования страницы.

2020-10-05 20:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-06 06:19 UTC, ShGKme approved these changes
Принято 👍

2020-10-06 06:19 UTC, merged