Task 1,2 for Lection4
js-tasks-ru/vue-20200925-2_nakonsta pull request #5
Opened 2020-10-11 18:18 UTC by Nakonsta

2020-10-11 18:24 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```
```diff
ContentTabs
+ ContentTabs должен иметь обязательный параметр список tabs
+ ContentTabs должен рендерить список вкладок
+ Активная вкладка должна иметь класс content-tabs__tab_active
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-11 19:01 UTC, ShGKme requested changes
Задача ScrollBehavior принята.
По задаче ContentTab требуется доработка...

2020-10-11 19:01 UTC, ShGKme commented on 04-SPA/01-ContentTabs/components/ContentTabs.vue
> +      <router-view :prop="this.$parent.prop"/>
Из условия: 
> `router-view` будет передаваться через слот компонента по умолчанию

Родитель передаёт `<router-view>` и сам же передаёт параметры

2020-10-11 21:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-11 21:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-12 05:35 UTC, ShGKme approved these changes
Принято 👍

2020-10-12 05:36 UTC, merged